# Generated by Django 2.1.5 on 2020-01-02 03:56

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now()),
            preserve_default=False,
        ),
    ]
